workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

default:
  tags:
    - xe
  before_script:
    - echo -e "\e[0Ksection_start:$(date +%s):install_dependencies[collapsed=true]\r\e[0KInstall dependencies"
    - apt update
    - apt install --yes
        git perl-doc
        build-essential ccache
        bc gawk flex bison libelf-dev libpci-dev libiberty-dev autoconf xz-utils
    - echo -e "\e[0Ksection_end:$(date +%s):install_dependencies\r\e[0K"

stages:
  - lint
  - build

lint-checkpatch-job:
  stage: lint
  allow_failure: true
  # TODO: move to using dim from maintainer-tools
  script:
    - echo "checkpatch code ${CI_MERGE_REQUEST_DIFF_BASE_SHA}..HEAD..."
    - ./scripts/checkpatch.pl
        -q --emacs --strict --show-types
        --max-line-length=100
        --ignore=BIT_MACRO,SPLIT_STRING,LONG_LINE_STRING,BOOL_MEMBER
        -g ${CI_MERGE_REQUEST_DIFF_BASE_SHA}..HEAD

lint-docs-job:
  stage: lint
  script:
    - echo "kernel-doc lint..."
    - find drivers/gpu/drm/xe/ -name '*.[ch]'
        -not -path 'drivers/gpu/drm/xe/display/*'
        -not -path drivers/gpu/drm/xe/i915_utils.h  |
        xargs ./scripts/kernel-doc -Werror  -none

.ccache-setup:
  variables:
    CCACHE_COMPILERCHECK: "content"
    CCACHE_COMPRESS: "true"
    CCACHE_DIR: /cache/xe-kernel/ccache
  # Use ccache transparently, and print stats before/after
  before_script:
    - !reference [default, before_script]
    - export PATH="/usr/lib/ccache:$PATH"
    - export CCACHE_BASEDIR="$PWD"
    - echo -e "\e[0Ksection_start:$(date +%s):ccache_before[collapsed=true]\r\e[0Kccache stats before build"
    - ccache --show-stats
    - echo -e "\e[0Ksection_end:$(date +%s):ccache_before\r\e[0K"
  after_script:
    - echo -e "\e[0Ksection_start:$(date +%s):ccache_after[collapsed=true]\r\e[0Kccache stats after build"
    - ccache --show-stats
    - echo -e "\e[0Ksection_end:$(date +%s):ccache_after\r\e[0K"

build-job:
  extends: .ccache-setup
  stage: build
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.freedesktop.org/drm/xe/ci.git .ci

    - echo -e "\e[0Ksection_start:$(date +%s):build_x86_64[collapsed=true]\r\e[0KBuild x86-64"
    - mkdir -p build64
    - cat .ci/kernel/kconfig > build64/.config
    - make O=build64 olddefconfig
    - make O=build64 -j$(nproc)
    - echo -e "\e[0Ksection_end:$(date +%s):build_x86_64\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):build_x86_64_warnings[collapsed=true]\r\e[0KBuild x86-64 - xe with W=1"
      # CONFIG_DRM_XE_DISPLAY currently breaks build with W=1. Just disable it for now
    - ./scripts/config --file build64/.config --disable CONFIG_DRM_XE_DISPLAY
    - make O=build64 modules_prepare
    - make O=build64 M=drivers/gpu/drm/xe W=1 -j$(nproc)
    - echo -e "\e[0Ksection_end:$(date +%s):build_x86_64\r\e[0K"
