#!/usr/bin/bash
set -ex

SRC_DIR=${CI_KERNEL_SRC_DIR:-.}

# everything in this script is relative to the kernel src
cd "$SRC_DIR"

find drivers/gpu/drm/xe/ \
	-name '*.[ch]' \
	-not -path 'drivers/gpu/drm/xe/display/*' \
	| xargs ./scripts/kernel-doc -Werror  -none \
	'drivers/gpu/drm/drm_gpusvm.c' \
	'drivers/gpu/drm/drm_pagemap.c' \
	'include/drm/drm_gpusvm.h' \
	'include/drm/drm_pagemap.h' \
	'include/uapi/drm/xe_drm.h'
